version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/app
      - ./.conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
    depends_on:
      - mysql
    volumes:
      - ./:/app
      - ./.conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf

  mysql:
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./docker-entrypoint-init:/docker-entrypoint-initdb.d
