UsersSearch\User:
  type: entity
  table: users
  options:
    charset: utf8mb4
    collate: utf8mb4_unicode_ci
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      length: 100
    lastName:
      type: string
      length: 100
