Feature: Users Search

  Scenario: Searching Users
    When I search the terms "John"
    Then I should get the following results:
      | firstName | lastName |
      | John | Abraham |
      | John | Allan |
      | John | Alsop |
      | John | Arnold |
      | John | Avery |
      | John | Bailey |
      | John | Baker |
      | John | Black |
      | John | Blake |
      | John | Brown |
      | John | Burgess |
      | John | Churchill |
      | John | Coleman |
      | John | Cornish |
      | John | Davidson |
      | John | Davies |
      | John | Dickens |
      | John | Forsyth |
      | John | Forsyth |
      | John | Forsyth |
      | John | Fraser |
      | John | Fraser |
      | John | Gibson |
      | John | Gill |
      | John | Graham |
      | John | Harris |
      | John | Hart |
      | John | Henderson |
      | John | Hodges |
      | John | Hudson |
      | John | Johnston |
      | John | Kelly |
      | John | Kelly |
      | John | Knox |
      | John | Lawrence |
      | John | Lawrence |
      | John | Lewis |
      | John | Lyman |
      | John | Lyman |
      | John | Mackay |
      | John | Mackenzie |
      | John | Marshall |
      | John | Mathis |
      | John | May |
      | John | Mitchell |
      | John | Murray |
      | John | Newman |
      | John | Ogden |
      | John | Paige |
      | John | Parsons |
      | John | Paterson |
      | John | Peake |
      | John | Peake |
      | John | Peters |
      | John | Quinn |
      | John | Randall |
      | John | Randall |
      | John | Robertson |
      | John | Ross |
      | John | Russell |
      | John | Sanderson |
      | John | Scott |
      | John | Simpson |
      | John | Simpson |
      | John | Sutherland |
      | John | Thomson |
      | John | Vance |
      | John | Vaughan |
      | John | Walker |
      | John | Watson |
      | John | Welch |
      | John | Welch |
      | John | White |
      | John | Wilkins |
      | John | Wright |
      | John | Young |

  Scenario: Searching Users Filtering Duplicates
    When I search the terms "John" filtering duplicates
    Then I should get the following results:
      | firstName | lastName |
      | John | Abraham |
      | John | Allan |
      | John | Alsop |
      | John | Arnold |
      | John | Avery |
      | John | Bailey |
      | John | Baker |
      | John | Black |
      | John | Blake |
      | John | Brown |
      | John | Burgess |
      | John | Churchill |
      | John | Coleman |
      | John | Cornish |
      | John | Davidson |
      | John | Davies |
      | John | Dickens |
      | John | Forsyth |
      | John | Fraser |
      | John | Gibson |
      | John | Gill |
      | John | Graham |
      | John | Harris |
      | John | Hart |
      | John | Henderson |
      | John | Hodges |
      | John | Hudson |
      | John | Johnston |
      | John | Kelly |
      | John | Knox |
      | John | Lawrence |
      | John | Lewis |
      | John | Lyman |
      | John | Mackay |
      | John | Mackenzie |
      | John | Marshall |
      | John | Mathis |
      | John | May |
      | John | Mitchell |
      | John | Murray |
      | John | Newman |
      | John | Ogden |
      | John | Paige |
      | John | Parsons |
      | John | Paterson |
      | John | Peake |
      | John | Peters |
      | John | Quinn |
      | John | Randall |
      | John | Robertson |
      | John | Ross |
      | John | Russell |
      | John | Sanderson |
      | John | Scott |
      | John | Simpson |
      | John | Sutherland |
      | John | Thomson |
      | John | Vance |
      | John | Vaughan |
      | John | Walker |
      | John | Watson |
      | John | Welch |
      | John | White |
      | John | Wilkins |
      | John | Wright |
      | John | Young |
